import type { NewCollection, NewProduct } from './schema';

export const SEED_COLLECTIONS: (NewCollection & { id: number })[] = [
  {
    id: 1,
    slug: 'haibat-majmua',
    name: 'HAIBAT MAJMUA',
    fabricType: 'Premium Cotton',
    tagline: 'Understated Royal Dignity',
    description: 'Refined cotton fabrics designed for effortless comfort, everyday elegance and timeless Pakistani style.',
    royalStory: 'In the quiet courtyards of ancestral havelis, dignity was never shouted; it was whispered in the crisp fall of combed Egyptian cotton. Haibat Majmua embodies this quiet authority. Woven from long-staple fibres with natural lustre, it bestows a composure that commands the room before a single word is uttered. For the man whose presence is an unspoken law.',
    image: '/images/haibat_cotton.jpg',
    featured: true,
  },
  {
    id: 2,
    slug: 'mehrab-intikhab',
    name: 'MEHRAB INTIKHAB',
    fabricType: 'Wash & Wear',
    tagline: 'Tradition Refined for the Modern Era',
    description: 'Versatile wash & wear fabrics engineered for a polished look with everyday practicality.',
    royalStory: 'When the heritage of the darbar steps into the rhythm of the modern metropolis, Mehrab Intikhab is born. Engineered with advanced microtwill weaving, this fabric remains immaculate throughout long days of statecraft and travel. A fluid, crease-resistant drape that honours our virasat while meeting the unyielding demands of the contemporary leader.',
    image: '/images/mehrab_washwear.jpg',
    featured: true,
  },
  {
    id: 3,
    slug: 'raees-riwayat',
    name: 'RAEES RIWAYAT',
    fabricType: 'Original Latha',
    tagline: 'Generations of Stature & Heritage',
    description: 'Traditional original Latha fabric representing heritage, character and timeless craftsmanship.',
    royalStory: 'A fabric that has lived through generations of patriarchs and celebrations of the subcontinent. Raees Riwayat represents pure, uncompromised Latha — crisp, structured, and resonant with the unmistakable rustle of authentic starch. It is the fabric of Eid mornings, ancestral darbars, and solemn occasions where waqar and shan are paramount.',
    image: '/images/raees_latha.jpg',
    featured: true,
  },
];

export const SEED_PRODUCTS: (NewProduct & { id: number })[] = [
  // --- HAIBAT MAJMUA (Premium Cotton) ---
  {
    id: 101,
    slug: 'haibat-royal-egyptian-giza-cotton-chalk-white',
    name: 'Haibat Royal Giza Cotton · Pure Chalk White',
    collectionSlug: 'haibat-majmua',
    fabricType: 'Premium Cotton',
    price: 8500,
    originalPrice: 9500,
    availability: 'IN STOCK',
    image: '/images/haibat_cotton.jpg',
    secondaryImage: '/images/fabric_texture.jpg',
    description: '100% Extra Long Staple Egyptian Giza Cotton spun into a featherweight yet dense weave, finished with a subtle silky touch for exceptional breathability and noble drape.',
    descriptionUrdu: '100 فیصد خالص مصری گیزا کاٹن سے تیار کردہ نفیس اور ہلکا پھلکا کپڑا، جو اپنی ریشمی ملائمت، بہترین ہوا داری اور شاہانہ وقار کے لیے اپنی مثال آپ ہے۔',
    descriptionArabic: 'قطن مصري فاخر من سلالة جيزة طويل التيلة بنسبة 100%، منسوج بحرفية عالية ليمنحك ملمساً حريرياً ناعماً وتهوية استثنائية مع إطلالة ملكية مهيبة.',
    royalTale: 'Like fresh lime plaster under the morning sun of an imperial haveli, this pure chalk white fabric is the quintessential choice for Jummah prayers, formal gatherings, and traditional Pakistani ceremonies.',
    texture: 'Crisp Egyptian Weave with Natural Silky Handfeel',
    recommendedUse: 'Jummah Prayers, Formal Haveli Gatherings & High Summer Wear',
    careInstructions: 'Gentle hand wash or machine cycle in cold water. Mild detergent only. Dry in shade. Warm steam iron while slightly damp.',
    meters: '4.5 Meters (56" Width) · Full Shalwar Kameez Cut',
    isFeatured: true,
    colorName: 'Pure Chalk White',
    weaveType: '120/2 Combed Giza Cotton',
  },
  {
    id: 102,
    slug: 'haibat-darbar-shadow-cotton-onyx-black',
    name: 'Haibat Darbar Shadow Cotton · Deep Onyx Black',
    collectionSlug: 'haibat-majmua',
    fabricType: 'Premium Cotton',
    price: 8900,
    originalPrice: 9900,
    availability: 'IN STOCK',
    image: '/images/hero_darbar.jpg',
    secondaryImage: '/images/haibat_cotton.jpg',
    description: 'Deep sulphur-dyed jet black cotton with zero colour bleeding, engineered for solemn evening occasions and commanding traditional silhouettes.',
    descriptionUrdu: 'گہرے پائیدار سیاہ رنگ میں رنگی گئی اعلیٰ معیار کی کاٹن، جس کا رنگ کبھی مدہم نہیں پڑتا؛ شام کی باوقار محفلوں اور روایتی شاہانہ لباس کے لیے بہترین انتخاب۔',
    descriptionArabic: 'قطن أسود ملكي عميق مصبوغ بتقنية ثبات اللون الفائقة، مصمم خصيصاً للمناسبات المسائية الرسمية والإطلالات التراثية ذات الهيبة والوقار.',
    royalTale: 'In the court of kings, the black robe was the symbol of justice, resolve, and steadfast governance. The deep dye penetrates the core of each yarn, retaining its resolute darkness wash after wash.',
    texture: 'Substantial Medium-Weight Cotton with Matte Finish',
    recommendedUse: 'Evening Darbars, Formal Dinners & Solemn Traditional Events',
    careInstructions: 'Cold hand wash separately for the first wash. Do not bleach. Dry inside out away from direct harsh sunlight.',
    meters: '4.5 Meters (56" Width) · Full Shalwar Kameez Cut',
    isFeatured: true,
    colorName: 'Onyx Black',
    weaveType: '100/2 Double Ply Premium Cotton',
  },
  {
    id: 103,
    slug: 'haibat-daur-e-khaas-cotton-pearl-cream',
    name: 'Haibat Daur-e-Khaas Cotton · Raw Pearl Cream',
    collectionSlug: 'haibat-majmua',
    fabricType: 'Premium Cotton',
    price: 8200,
    originalPrice: null,
    availability: 'IN STOCK',
    image: '/images/haibat_cotton.jpg',
    secondaryImage: '/images/fabric_texture.jpg',
    description: 'An unbleached natural cream cotton woven with organic slub undertones, celebrating the ancient artisanal texture of heirloom cloth.',
    descriptionUrdu: 'قدرتی پرل کریم رنگت میں بنی ہوئی خالص کاٹن، جو قدیم روایتی دستکاری اور خاندانی وجاہت کی عکاسی کرتی ہے۔',
    descriptionArabic: 'قطن طبيعي بلون اللؤلؤ الكريمي غير المبيض، منسوج بلمسات عضوية أصيلة تحتفي بالحرفية التراثية العريقة للأقمشة الملكية الفاخرة.',
    royalTale: 'Woven with gentle organic variations that recall the handlooms of ancestral Punjab, this warm cream fabric brings an earthy, grounded nobility to the wearer.',
    texture: 'Organic Micro-Slub Texture with Soft Drape',
    recommendedUse: 'Daytime Functions, Informal Family Mehfils & Summer Elegance',
    careInstructions: 'Gentle cycle, cold water. Use fabric conditioner to maintain natural cotton softness. Steam press.',
    meters: '4.5 Meters (56" Width) · Full Shalwar Kameez Cut',
    isFeatured: false,
    colorName: 'Raw Pearl Cream',
    weaveType: 'Organic Combed Cotton Poplin',
  },
  {
    id: 104,
    slug: 'haibat-asal-pima-cotton-desert-khaki',
    name: 'Haibat Asal Pima Cotton · Desert Khaki',
    collectionSlug: 'haibat-majmua',
    fabricType: 'Premium Cotton',
    price: 8700,
    originalPrice: 9600,
    availability: 'LIMITED RUN',
    image: '/images/fabric_texture.jpg',
    secondaryImage: '/images/hero_darbar.jpg',
    description: 'American Supima cotton spun with exquisite tensile strength, dyed in a regal desert sand hue that pairs impeccably with dark Peshawari chappals.',
    descriptionUrdu: 'مضبوط اور نفیس امریکن سوپیما کاٹن سے تیار کردہ صحرائی خاکی رنگ کا کپڑا، جو پشاوری چپل اور روایتی پاکستانی انداز کے ساتھ بے مثال جچتا ہے۔',
    descriptionArabic: 'قطن سوبيما فاخر ذو متانة فائقة، مصبوغ بلون رمال الصحراء الملكي ليمنحك حضوراً كلاسيكياً أنيقاً يتناغم مع التراث الأصيل.',
    royalTale: 'Reflecting the sunlit bastions of the Lahore Fort, this desert khaki hue is timeless, dignified, and effortlessly masculine.',
    texture: 'Structured Fine Satin Weave with Crisp Hand',
    recommendedUse: 'Outdoor Royal Events, Travel, Daily Aristocratic Wear',
    careInstructions: 'Normal wash with like colours. Tumble dry low or air dry. Medium iron.',
    meters: '4.5 Meters (56" Width) · Full Shalwar Kameez Cut',
    isFeatured: true,
    colorName: 'Desert Khaki',
    weaveType: 'Supima Twill Weave',
  },

  // --- MEHRAB INTIKHAB (Wash & Wear) ---
  {
    id: 201,
    slug: 'mehrab-royal-navy-wrinkle-free-suiting',
    name: 'Mehrab Royal Navy · Liquid Suiting',
    collectionSlug: 'mehrab-intikhab',
    fabricType: 'Wash & Wear',
    price: 7800,
    originalPrice: 8800,
    availability: 'IN STOCK',
    image: '/images/mehrab_washwear.jpg',
    secondaryImage: '/images/hero_darbar.jpg',
    description: 'Engineered with a high-twist Japanese micro-fibre blend, this royal navy fabric flows like water while maintaining razor-sharp creases throughout the day.',
    descriptionUrdu: 'جاپانی مائیکرو فائبر دھاگوں کے خاص امتزاج سے تیار کردہ رائل نیوی واش اینڈ ویئر، جو دن بھر شکن سے پاک رہتا ہے اور پانی کی طرح رواں ڈریپ دیتا ہے۔',
    descriptionArabic: 'نسيج كحلي ملكي مطور من ألياف يابانية دقيقة عالية البرم، ينساب بنعومة فائقة مع الحفاظ على مظهر مكوي وأنيق طوال اليوم دون تجعد.',
    royalTale: 'A colour reminiscent of the night sky over the Mughal pleasure gardens. For the modern leader whose days transition from the boardroom to family celebrations without a crease in his composure.',
    texture: 'Fluid Crease-Resistant Drape with Subtle Sheen',
    recommendedUse: 'Executive Gatherings, Wedding Functions & Travel',
    careInstructions: 'Machine wash on delicate. Wash & Wear finish requires little to no ironing. Hang dry immediately.',
    meters: '4.5 Meters (56" Width) · Full Shalwar Kameez Cut',
    isFeatured: true,
    colorName: 'Royal Midnight Navy',
    weaveType: 'High-Twist Poly-Viscose Micro-Twill',
  },
  {
    id: 202,
    slug: 'mehrab-waqar-platinum-steel-wash-wear',
    name: 'Mehrab Waqar · Platinum Steel Gray',
    collectionSlug: 'mehrab-intikhab',
    fabricType: 'Wash & Wear',
    price: 7500,
    originalPrice: 8500,
    availability: 'IN STOCK',
    image: '/images/mehrab_washwear.jpg',
    secondaryImage: '/images/fabric_texture.jpg',
    description: 'Cool slate-platinum undertones combined with featherweight four-way comfort drape. Perfect for all seasons with unmatched wrinkle recovery.',
    descriptionUrdu: 'پلاٹینم اسٹیل گرے رنگت اور چاروں طرف آرام دہ لچک کے ساتھ ہر موسم کے لیے موزوں کپڑا، جو شکنوں سے مکمل محفوظ رہتا ہے۔',
    descriptionArabic: 'قماش بلون رمادي بلاتيني بارد يتميز بخفة الوزن والانسيابية المريحة في جميع الفصول، مع قدرة فائقة على مقاومة التجعد.',
    royalTale: 'The cold steel of royal armour translated into modern luxury. It projects calm resolve, intellectual poise, and unwavering dignity in any company.',
    texture: 'Silky Peach-Skin Surface with Cool-Touch Breathability',
    recommendedUse: 'All-Day Corporate Wear, Jummah, Evening Dinners',
    careInstructions: 'Machine washable. No dry cleaning required. Quick dry technology.',
    meters: '4.5 Meters (56" Width) · Full Shalwar Kameez Cut',
    isFeatured: false,
    colorName: 'Platinum Steel Gray',
    weaveType: 'Bespoke Micro-Filament Blend',
  },
  {
    id: 203,
    slug: 'mehrab-sultan-deep-midnight-black',
    name: 'Mehrab Sultan · Deep Obsidian Black',
    collectionSlug: 'mehrab-intikhab',
    fabricType: 'Wash & Wear',
    price: 8200,
    originalPrice: 9200,
    availability: 'IN STOCK',
    image: '/images/hero_darbar.jpg',
    secondaryImage: '/images/mehrab_washwear.jpg',
    description: 'An intensely pigmented obsidian black wash and wear fabric with high thermal resistance and a majestic fluid fall that accentuates the masculine silhouette.',
    descriptionUrdu: 'گہرے سیاہ رنگ کا شاہانہ واش اینڈ ویئر کپڑا جو اپنی بھاری اور باوقار فال کی بدولت مردانہ شخصیت میں رعب اور دلکشی پیدا کرتا ہے۔',
    descriptionArabic: 'قماش واش آند وير أسود داكن غني بالصبغة، يتميز بمقاومة حرارية عالية وانسيابية ملكية تبرز فخامة التصميم الرجالي.',
    royalTale: 'Worn by men who understand that true power needs no adornment. The fabric retains its pitch-black lustre even under the intense lighting of royal wedding halls.',
    texture: 'Heavy Fall with Crisp Pleating Retention',
    recommendedUse: 'Formal Receptions, Barat Ceremonies, Winter & Autumn Elegance',
    careInstructions: 'Cold water wash. Do not use chlorine bleach. Quick press with low iron if required.',
    meters: '4.5 Meters (56" Width) · Full Shalwar Kameez Cut',
    isFeatured: true,
    colorName: 'Obsidian Black',
    weaveType: 'Heavyweight Suiting Wash & Wear',
  },
  {
    id: 204,
    slug: 'mehrab-intikhab-cocoa-bronze-texture',
    name: 'Mehrab Intikhab · Royal Cocoa Bronze',
    collectionSlug: 'mehrab-intikhab',
    fabricType: 'Wash & Wear',
    price: 7600,
    originalPrice: null,
    availability: 'IN STOCK',
    image: '/images/mehrab_washwear.jpg',
    secondaryImage: '/images/fabric_texture.jpg',
    description: 'A rich roasted cocoa brown shade with warm bronze undertones, creating a distinctive and tasteful departure from conventional menswear palettes.',
    descriptionUrdu: 'کوکو براؤن اور برانز کی دلکش آمیزش سے تیار کردہ منفرد واش اینڈ ویئر، جو روایتی رنگوں سے ہٹ کر ایک اعلیٰ اور نفیس ذوق کی نمائندگی کرتا ہے۔',
    descriptionArabic: 'درجة غنية من البني الكاكاوي المحمص مع لمسات برونزية دافئة، تمنحك تميزاً راقياً وذوقاً رفيعاً في المناسبات المسائية والشتوية.',
    royalTale: 'Inspired by the warm wooden woodwork and brass accents of ancient darbar ceilings, this fabric brings an understated warmth and refined taste.',
    texture: 'Supple Medium-Drape with Satin Highlights',
    recommendedUse: 'Qawwali Nights, Winter Mehfils & Festive Get-Togethers',
    careInstructions: 'Machine wash gentle. Dry on hanger to eliminate need for pressing.',
    meters: '4.5 Meters (56" Width) · Full Shalwar Kameez Cut',
    isFeatured: false,
    colorName: 'Cocoa Bronze',
    weaveType: 'Textured Poly-Viscose Weave',
  },

  // --- RAEES RIWAYAT (Original Latha) ---
  {
    id: 301,
    slug: 'raees-asli-shahi-latha-68000-pure-snow-white',
    name: 'Raees Asli Shahi Latha 68000 · Pure Snow White',
    collectionSlug: 'raees-riwayat',
    fabricType: 'Original Latha',
    price: 9500,
    originalPrice: 10800,
    availability: 'IN STOCK',
    image: '/images/raees_latha.jpg',
    secondaryImage: '/images/haibat_cotton.jpg',
    description: 'The pinnacle of authentic Pakistani latha fabric. Spun with 68000-grade high-density count, producing the iconic crisp traditional handfeel and legendary snap.',
    descriptionUrdu: 'اصلی پاکستانی شاہی لتھہ کا شاہکار؛ 68000 گریڈ کی اعلیٰ بُنت سے تیار کردہ خالص سفید کپڑا جو اپنی روایتی کڑک اور شاندار آواز کے لیے مشہور ہے۔',
    descriptionArabic: 'قمة أقمشة اللثه الباكستانية الأصيلة بدرجة كثافة 68000، تمنحك القوام المتماسك التقليدي والملمس الملكي الناصع البياض.',
    royalTale: 'When a patriarch stands before his family on Eid morning, this is the cloth he wears. Pristine, stiff, unwavering. It does not yield to modern shortcuts; it honours the ancestral standard of Pakistani menswear.',
    texture: 'Authentic Traditional Starch Finish with Resonant Crisp Rustle',
    recommendedUse: 'Eid Day, Nikah Ceremonies, Ancestral Family Traditions',
    careInstructions: 'Traditional starching recommended for authentic crisp finish. Wash with mild soap in cold water. Heavy steam press.',
    meters: '4.5 Meters (56" Width) · Full Shalwar Kameez Cut',
    isFeatured: true,
    colorName: 'Pure Snow White',
    weaveType: 'Grade 68,000 High-Density Authentic Latha',
  },
  {
    id: 302,
    slug: 'raees-virasat-heritage-latha-5000-imperial-finish',
    name: 'Raees Virasat Heritage Latha 5000 · Imperial Crisp',
    collectionSlug: 'raees-riwayat',
    fabricType: 'Original Latha',
    price: 9200,
    originalPrice: 10200,
    availability: 'IN STOCK',
    image: '/images/raees_latha.jpg',
    secondaryImage: '/images/fabric_texture.jpg',
    description: 'A timeless staple of subcontinental menswear, offering balanced body, high tear resistance, and the immaculate formal presence of classic latha cloth.',
    descriptionUrdu: 'برصغیر کے روایتی مردانہ لباس کی لازوال پہچان؛ مضبوط بُنت، متوازن وزن اور باوقار رسمی تقاریب کے لیے کلاسک وراثت لتھہ۔',
    descriptionArabic: 'رمز الأصالة والعراقة في الأزياء الرجالية التقليدية، يجمع بين القوام المتوازن والمتانة العالية والحضور الرسمي المهيب.',
    royalTale: 'Virasat means legacy, and this cloth is woven precisely to endure. Tailored into traditional loose-cut Shalwars and straight-collar Kameez, it embodies royal heritage.',
    texture: 'Structured Cotton Finish with Formal Body',
    recommendedUse: 'Official Functions, Friday Congregated Prayers & Festivals',
    careInstructions: 'Cold water soak before tailoring. Hand wash with starch for traditional stiff drape.',
    meters: '4.5 Meters (56" Width) · Full Shalwar Kameez Cut',
    isFeatured: true,
    colorName: 'Crisp White',
    weaveType: 'Grade 50,000 Heritage Latha Cotton',
  },
  {
    id: 303,
    slug: 'raees-darbari-bleached-cotton-latha-warm-ivory',
    name: 'Raees Darbari Latha · Warm Ivory Sheen',
    collectionSlug: 'raees-riwayat',
    fabricType: 'Original Latha',
    price: 8900,
    originalPrice: null,
    availability: 'LIMITED RUN',
    image: '/images/raees_latha.jpg',
    secondaryImage: '/images/haibat_cotton.jpg',
    description: 'A rare semi-bleached ivory latha that combines the crisp discipline of traditional starched cotton with a gentle warm undertone that softens the facial complexion.',
    descriptionUrdu: 'کلف شدہ کاٹن کی روایتی نفاست اور ہلکی آئیوری چمک کا حسین امتزاج، جو چہرے کی جاذبیت اور شخصیت کے وقار کو دوبالا کرتا ہے۔',
    descriptionArabic: 'لثه عاجية نادرة تجمع بين تماسك القطن التقليدي المنشى ولمسة لونية دافئة تضفي وقاراً ونبلاً هادئاً.',
    royalTale: 'For men who seek the discipline of original latha but prefer the softened majesty of warm ivory. It exudes age-old dignity and understated nobility.',
    texture: 'Firm Handfeel with Natural Cotton Sheen',
    recommendedUse: 'Family Dinners, Traditional Mehndi, Daytime Festivities',
    careInstructions: 'Hand wash with mild liquid detergent. Starch lightly if preferred. Press with heavy iron.',
    meters: '4.5 Meters (56" Width) · Full Shalwar Kameez Cut',
    isFeatured: false,
    colorName: 'Warm Ivory',
    weaveType: 'Fine Count Semi-Bleached Latha',
  },
  {
    id: 304,
    slug: 'raees-shan-e-mughal-traditional-latha-heavy-density',
    name: 'Raees Shan-e-Mughal · Heavy Density Latha',
    collectionSlug: 'raees-riwayat',
    fabricType: 'Original Latha',
    price: 9800,
    originalPrice: 11000,
    availability: 'IN STOCK',
    image: '/images/raees_latha.jpg',
    secondaryImage: '/images/hero_darbar.jpg',
    description: 'Our most substantial latha fabric cut. High grammage and ultra-tight warp packing yield an opaque, majestic fabric that holds its crease through the longest occasions.',
    descriptionUrdu: 'ہمارے مجموعے کا سب سے بھاری اور گھنی بُنت والا شاہی لتھہ؛ مکمل طور پر غیر شفاف اور طویل تقریبات میں بھی اپنی کڑک برقرار رکھنے والا بے مثال کپڑا۔',
    descriptionArabic: 'أفخر وأثقل قطع اللثه الملكية لدينا؛ منسوج بكثافة خيوط فائقة تضمن عدم الشفافية وثبات الكي طوال المناسبات الكبرى.',
    royalTale: 'The definitive cloth of honor. Zero transparency, immense presence, and a hand that commands respect from master tailors across the country.',
    texture: 'Heavyweight High-Density Starch Finish',
    recommendedUse: 'Wedding Ceremonies, Royal Darbar Assemblies & Prestigious Gatherings',
    careInstructions: 'Professional laundry or cold hand wash. Heavy starch and hot iron for best results.',
    meters: '4.5 Meters (56" Width) · Full Shalwar Kameez Cut',
    isFeatured: true,
    colorName: 'Imperial Chalk White',
    weaveType: 'Heavy Density Imperial Latha',
  },
];
